 
 
 
const  DataMovies=
 [
  {id:"1", name: "Nemo", description:"  Finding Nemo is a 2003 American computer-animated adventure film produced by Pixar Animation Studios and released by Walt Disney Pictures.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3Za-zIALUUm5BJQGk68dSIIaL2Smt5A1Atw&usqp=CAU", rating:"5", trailer:'https://youtu.be/wZdpNglLbt8'},
  {id:"2", name: "Industructibles 2", description:"Incredibles 2 is a 2018 American computer-animated superhero film produced by Pixar Animation Studios and released by Walt Disney Pictures.", image:"https://cdn.shopify.com/s/files/1/1416/8662/products/incredibles_2_2018_french_grande_a_original_film_art_1200x.jpg?v=1588448598", rating:"3", trailer:'https://youtu.be/i5qOzqD9Rms'},
  {id:"3", name: "FROZEN 2", description:"Frozen II is a 2019 American computer-animated musical fantasy film produced by Walt Disney Animation Studios and distributed by Walt Disney Studios Motion Pictures. ", image:"https://cdn.europosters.eu/image/750/posters/frozen-2-magic-i83468.jpg", rating:"5", trailer:'https://youtu.be/Zi4LMpSDccc'},
  {id:"4", name: "Hotel Transylvania", description:"Hotel Transylvania is a media franchise created by comedy writer Todd Durham. It consists of three theatrical films (along with an upcoming film), three graphic novels and two short films produced by Sony Pictures Animation, as well as a traditionally-animated TV series broadcast on Disney Channel and several video games.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtjPjT6h-jXU2jeqhumQB7Vs227344CEIfNo2Kic6cu6C6maDd", rating:"4", trailer:'https://youtu.be/q4RK3jY7AVk'},
  {id:"5", name: "UP", description:"Up is a 2009 American computer-animated comedy-drama adventure film produced by Pixar Animation Studios and released by Walt Disney Pictures.", image:"https://i.pinimg.com/originals/85/45/03/854503affab6d3e789cca6c7d393b5b1.jpg", rating:"4", trailer:'https://youtu.be/pkqzFUhGPJg'},
  {id:"6", name: "Monsters VS Aliens", description:"Monsters vs. Aliens is a 2009 American computer-animated science fiction comedy film produced by DreamWorks Animation and distributed by Paramount Pictures.", image:"https://images-na.ssl-images-amazon.com/images/I/81HmlLISVIL._AC_SY445_.jpg", rating:"2", trailer:'https://youtu.be/-ciUH9qJ-d8'},
  {id:"7", name: "Baby Boss", description:"The Boss Baby is a 2017 American computer-animated comedy film[4] produced by DreamWorks Animation and distributed by 20th Century Fox.", image:"http://www.cinema.com.my/images/movies/2017/7bossbaby_sg00_450.jpg", rating:"4", trailer:'https://youtu.be/O2Bsw3lrhvs'},
  {id:"8", name: "Inside Out", description:"Inside Out is a 2015 American computer-animated comedy film produced by Pixar Animation Studios and distributed by Walt Disney Studios Motion Pictures.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-ld9Yqe_Np_SzgrU5MT-FrB0YLGkvCSz-IQ&usqp=CAU", rating:"5", trailer:'https://youtu.be/yRUAzGQ3nSY'},
  {id:"9", name: "The croods", description:"The Croods is a 2013 American computer-animated adventure comedy film produced by DreamWorks Animation and distributed by 20th Century Fox.", image:"https://i.ytimg.com/vi/zhzSKw_3P6A/movieposter_en.jpg", rating:"2", trailer:'https://youtu.be/VeG3Zmk08UU'},
  {id:"8", name: "Home", description:"Home is a 2015 American computer-animated science-fiction comedy film[4][5] produced by DreamWorks Animation and distributed by 20th Century Fox.", image:"https://fr.web.img6.acsta.net/pictures/14/12/04/10/52/050418.jpg", rating:"5", trailer:'https://youtu.be/G9F6VhFY4wY'},
  {id:"10", name: "The Adams Family", description:"The Addams Family is a 2019 computer-animated supernatural black comedy film directed by Conrad Vernon and Greg Tiernan and based on the characters created by Charles Addams.", image:"https://www.sideshow.com/wp/wp-content/uploads/2019/08/addams1.jpg", rating:"2", trailer: 'https://youtu.be/F7Ug863S8dQ'},
  {id:"11", name: "Finding Dorry", description:"8 Juin 2016", image:"https://www.arthipo.com/image/cache/catalog/poster/movie/1-758/pfilm328-finding-nemo-poster-cartoon-movie-poster-cizgi-film-posteri-1000x1000.jpg", rating:"4", trailer:'https://youtu.be/pSf-5vbVpAU'},
]
   export default DataMovies;